name: star-bank-infra

on:
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub Actions tab.
  push:
    branches:
      - '*'  # Trigger on any branch push
    paths-ignore:
      - 'scripts/**'  # Ignore changes in the `scripts` directory

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-B-UAT
  RESOURCE_GROUP_PROD: BCSAI2024-DEVOPS-STUDENTS-B-PROD
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: makenna

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
      - uses: actions/checkout@v4

      # Lint Bicep code
      - name: Run Bicep linter
        run: az bicep build --file ./main.bicep

      # Upload Bicep build artifact
      - name: Upload Bicep build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bicep-build
          path: ./main.bicep  # Adjust this path as necessary for your build output

  deploy-dev:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Download Bicep build artifact
      - name: Download Bicep build artifact
        uses: actions/download-artifact@v4
        with:
          name: bicep-build

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
      - name: Deploy Application Insights, Log Analytics, and Workbook to Dev
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./main.bicep
          parameters: ./parameters/dev.parameters.json
          deploymentName: starbank-dev

  deploy-uat:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'UAT'

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Download Bicep build artifact
      - name: Download Bicep build artifact
        uses: actions/download-artifact@v4
        with:
          name: bicep-build

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
      - name: Deploy Application Insights, Log Analytics, and Workbook to UAT
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./main.bicep
          parameters: ./parameters/uat.parameters.json
          deploymentName: starbank-uat

  deploy-prod:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Download Bicep build artifact
      - name: Download Bicep build artifact
        uses: actions/download-artifact@v4
        with:
          name: bicep-build

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
      - name: Deploy Application Insights, Log Analytics, and Workbook to Prod
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_PROD }}
          template: ./main.bicep
          parameters: ./parameters/prod.parameters.json
          deploymentName: starbank-prod
