name: star-bank-infra

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab
  pull_request:
    branches:
      - main
  push:
    branches:
      - '*'
    paths-ignore:
      - 'scripts/**'

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-B-UAT
  RESOURCE_GROUP_PROD: BCSAI2024-DEVOPS-STUDENTS-B-PROD
  SUBSCRIPTION_ID: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: makenna

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Bicep Linter
        run: |
          az bicep build --file ./main.bicep --only-show-errors --output json

  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Lint Bicep code
      - name: Run Bicep linter
        run: az bicep build --file ./main.bicep

      # Upload Bicep build artifact
      - name: Upload Bicep build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bicep-build
          path: ./main.bicep  # Adjust this path as necessary for your build output

  validate-dev:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Dev Deployment
        uses: azure/arm-deploy@v2
        with:
          scope: resourceGroup
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./main.bicep
          parameters: ./parameters/dev.parameters.json
          deploymentMode: Validate

  validate-uat:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate UAT Deployment
        uses: azure/arm-deploy@v2
        with:
          scope: resourceGroup
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./main.bicep
          parameters: ./parameters/uat.parameters.json
          deploymentMode: Validate

  validate-prod:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Prod Deployment
        uses: azure/arm-deploy@v2
        with:
          scope: resourceGroup
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_PROD }}
          template: ./main.bicep
          parameters: ./parameters/prod.parameters.json
          deploymentMode: Validate

  deploy-dev:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [build, validate-dev]
    environment:
      name: 'Development'

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Dev Infrastructure
        uses: azure/arm-deploy@v2
        with:
          scope: resourceGroup
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./main.bicep
          parameters: ./parameters/dev.parameters.json
          deploymentName: starbank-dev

  deploy-uat:
    if: github.event.pull_request.base.ref == 'main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [build, validate-uat]
    environment:
      name: 'UAT'

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy UAT Infrastructure
        uses: azure/arm-deploy@v2
        with:
          scope: resourceGroup
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./main.bicep
          parameters: ./parameters/uat.parameters.json
          deploymentName: starbank-uat

  deploy-prod:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [build, validate-prod, deploy-uat]
    environment:
      name: 'Production'

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Prod Infrastructure
        uses: azure/arm-deploy@v2
        with:
          scope: resourceGroup
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_PROD }}
          template: ./main.bicep
          parameters: ./parameters/prod.parameters.json
          deploymentName: starbank-prod