name: ie-bank-infra
on:
  workflow_dispatch: #Allows you to manually trigger the workflow from the GitHub Actions tab.
  pull_request:
      branches:
        - main
  push:
      branches:
        - '*'
      paths-ignore:
        - 'scripts/**'


env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-B-UAT
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: makenna

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bicep linter
        run: az bicep build --file ./main.bicep

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: Development

    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Debug Key Vault Secrets
        run: az keyvault secret list --vault-name makenna-keyvault-dev --query "[].name" -o tsv
        
      - name: Retrieve secrets from Key Vault
        run: |
          az keyvault secret show --name ACR-Admin-Username --vault-name makenna-keyvault-dev --query value -o tsv > acrAdminUsername.txt
          az keyvault secret show --name ACR-Admin-Password0 --vault-name makenna-keyvault-dev --query value -o tsv > acrAdminPassword0.txt
          az keyvault secret show --name ACR-Admin-Password1 --vault-name makenna-keyvault-dev --query value -o tsv > acrAdminPassword1.txt
      - name: Deploy to Development
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./infra/main.bicep
          parameters: >
            ./infra/parameters/dev.parameters.json 
            dockerRegistryImageName=my-container-image
            environmentType=nonprod
            userAlias=makenna
            containerRegistryName=makennaacrdev
            acrAdminUsername=$(cat acrAdminUsername.txt)
            acrAdminPassword0=$(cat acrAdminPassword0.txt)
            acrAdminPassword1=$(cat acrAdminPassword1.txt)
            keyVaultName=makenna-keyvault-dev
            postgreSQLServerName=makenna-dbsrv-dev
            postgreSQLDatabaseName=makenna-db-dev
            appServicePlanName=makenna-asp-dev
            appServiceWebsiteBEName=makenna-be-dev
            appServiceWebsiteFEName=makenna-fe-dev
          deploymentName: ${{ env.USER_ALIAS }}-dev

  deploy-uat:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' && github.base_ref == 'main' || github.ref == 'refs/heads/main'
    environment: UAT

    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Retrieve secrets from Key Vault
        run: |
          az keyvault secret show --name ACR-Admin-Username --vault-name makenna-keyvault-uat --query value -o tsv > acrAdminUsername.txt
          az keyvault secret show --name ACR-Admin-Password0 --vault-name makenna-keyvault-uat --query value -o tsv > acrAdminPassword0.txt
          az keyvault secret show --name ACR-Admin-Password1 --vault-name makenna-keyvault-uat --query value -o tsv > acrAdminPassword1.txt
      - name: Deploy to UAT
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./infra/main.bicep
          parameters: >
            ./infra/parameters/uat.parameters.json
            dockerRegistryImageName=my-container-image
            environmentType=uat
            userAlias=makenna
            containerRegistryName=makennaacrdev
            acrAdminUsername=$(cat acrAdminUsername.txt)
            acrAdminPassword0=$(cat acrAdminPassword0.txt)
            acrAdminPassword1=$(cat acrAdminPassword1.txt)
            keyVaultName=makenna-keyvault-uat
            postgreSQLServerName=makenna-dbsrv-uat
            postgreSQLDatabaseName=makenna-db-uat
            appServicePlanName=makenna-asp-uat
            appServiceWebsiteBEName=makenna-be-uat
            appServiceWebsiteFEName=makenna-fe-uat
          deploymentName: ${{ env.USER_ALIAS }}-uat

