name: ie-bank-infra

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab
  pull_request:
    branches:
      - main
  push:
    branches:
      - '*'
    paths-ignore:
      - 'scripts/**'

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-B-UAT
  RESOURCE_GROUP_PROD: BCSAI2024-DEVOPS-STUDENTS-B-PROD
  SUBSCRIPTION_ID: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: makenna

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Lint Bicep code
      - name: Run Bicep linter
        run: az bicep build --file ./main.bicep

      # Upload Bicep build artifact
      - name: Upload Bicep build artifact
        uses: actions/upload-artifact@v3
        with:
          name: bicep-build
          path: ./main.bicep

  deploy-dev:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Download Bicep build artifact
      - name: Download Bicep build artifact
        uses: actions/download-artifact@v3
        with:
          name: bicep-build

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
      - name: Deploy to dev
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          scope: resourceGroup
          template: ./main.bicep
          parameters: ./parameters/dev.parameters.json
          deploymentName: ${{ env.USER_ALIAS }}-dev

  deploy-uat:
    if: github.event.pull_request.base.ref == 'main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'UAT'

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Download Bicep build artifact
      - name: Download Bicep build artifact
        uses: actions/download-artifact@v3
        with:
          name: bicep-build

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
      - name: Deploy to uat
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          scope: resourceGroup
          template: ./main.bicep
          parameters: ./parameters/uat.parameters.json
          deploymentName: ${{ env.USER_ALIAS }}-uat

  deploy-prod:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Download Bicep build artifact
      - name: Download Bicep build artifact
        uses: actions/download-artifact@v3
        with:
          name: bicep-build

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
      - name: Deploy to prod
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_PROD }}
          scope: resourceGroup
          template: ./main.bicep
          parameters: ./parameters/prod.parameters.json
          deploymentName: ${{ env.USER_ALIAS }}-prod